import React, { useState, useEffect } from 'react';
import { Info, ChevronDown, ChevronUp, Calculator, DollarSign } from 'lucide-react';

/**
 * AITouchValue Component Props Interface
 * Defines the configurable properties for the AI Touch Value™ calculator
 */
interface AITouchValueProps {
  /** Initial model earnings value in dollars (default: 0) */
  initialModelEarnings?: number;
  /** Initial training contribution score 0-100 (default: 50) */
  initialContributionScore?: number;
  /** Initial usage exposure score 0-100 (default: 50) */
  initialExposureScore?: number;
  /** Whether the inputs are editable (default: true) */
  editable?: boolean;
  /** Callback fired when calculation value changes */
  onCalculate?: (value: number) => void;
}

/**
 * Projection scenario interface for scenario cards
 */
interface ProjectionScenario {
  name: string;
  contributionScore: number;
  exposureScore: number;
  description: string;
}

/**
 * Fixed equity factor for AI Touch Value™ calculation (25%)
 * This represents the fixed creator compensation rate
 */
const EQUITY_FACTOR = 0.25;

/**
 * Maximum model earnings for slider (10 million dollars)
 */
const MAX_MODEL_EARNINGS = 10_000_000;

/**
 * Slider step for model earnings
 */
const EARNINGS_STEP = 1000;

/**
 * Formats a number as currency with locale-aware formatting
 * @param value - The numeric value to format
 * @param compact - Whether to use compact notation for large numbers
 * @returns Formatted currency string
 */
const formatCurrency = (value: number, compact: boolean = false): string => {
  if (compact && value >= 1_000_000) {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      notation: 'compact',
      maximumFractionDigits: 1,
    }).format(value);
  }
  
  if (compact && value >= 1_000) {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      notation: 'compact',
      maximumFractionDigits: 1,
    }).format(value);
  }

  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
};

/**
 * Calculates the AI Touch Value™ using the official formula
 * Formula: ModelEarnings × (TrainingContributionScore/100) × (UsageExposureScore/100) × EquityFactor
 * 
 * @param modelEarnings - Total revenue generated by the AI model
 * @param contributionScore - Training contribution score (0-100)
 * @param exposureScore - Usage exposure score (0-100)
 * @returns Calculated AI Touch Value rounded to 2 decimal places
 */
const calculateAITouchValue = (
  modelEarnings: number,
  contributionScore: number,
  exposureScore: number
): number => {
  const value = modelEarnings * (contributionScore / 100) * (exposureScore / 100) * EQUITY_FACTOR;
  return Math.round(value * 100) / 100; // Round to 2 decimal places
};

/**
 * Predefined projection scenarios for demonstrating value calculations
 */
const projectionScenarios: ProjectionScenario[] = [
  {
    name: 'Conservative',
    contributionScore: 25,
    exposureScore: 25,
    description: 'Low contribution and exposure',
  },
  {
    name: 'Moderate',
    contributionScore: 50,
    exposureScore: 50,
    description: 'Medium contribution and exposure',
  },
  {
    name: 'Optimistic',
    contributionScore: 75,
    exposureScore: 75,
    description: 'High contribution and exposure',
  },
];

/**
 * AITouchValue Component
 * 
 * Displays AI Touch Value™ monetary compensation estimates with interactive formula breakdown,
 * adjustable input sliders, real-time calculation updates, and projection scenarios.
 * 
 * The AI Touch Value™ estimates creator compensation based on the formula:
 * Value = ModelEarnings × (TrainingContributionScore/100) × (UsageExposureScore/100) × 0.25
 * 
 * @param props - Component properties
 * @returns JSX element rendering the AI Touch Value calculator
 */
const AITouchValue: React.FC<AITouchValueProps> = ({
  initialModelEarnings = 0,
  initialContributionScore = 50,
  initialExposureScore = 50,
  editable = true,
  onCalculate,
}) => {
  // State for input values
  const [modelEarnings, setModelEarnings] = useState<number>(initialModelEarnings);
  const [contributionScore, setContributionScore] = useState<number>(initialContributionScore);
  const [exposureScore, setExposureScore] = useState<number>(initialExposureScore);
  
  // State for calculated value
  const [calculatedValue, setCalculatedValue] = useState<number>(0);
  
  // State for explanation panel visibility
  const [isExplanationExpanded, setIsExplanationExpanded] = useState<boolean>(false);
  
  // State for precise earnings input
  const [earningsInputValue, setEarningsInputValue] = useState<string>(
    initialModelEarnings.toString()
  );

  /**
   * Effect to recalculate AI Touch Value™ when any input changes
   * Updates the calculated value and notifies parent via callback
   */
  useEffect(() => {
    const newValue = calculateAITouchValue(modelEarnings, contributionScore, exposureScore);
    setCalculatedValue(newValue);
    
    // Notify parent component of value change
    if (onCalculate) {
      onCalculate(newValue);
    }
  }, [modelEarnings, contributionScore, exposureScore, onCalculate]);

  /**
   * Handles changes to the model earnings slider
   */
  const handleEarningsSliderChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    const value = Number(e.target.value);
    setModelEarnings(value);
    setEarningsInputValue(value.toString());
  };

  /**
   * Handles changes to the model earnings text input
   */
  const handleEarningsInputChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    const inputValue = e.target.value;
    setEarningsInputValue(inputValue);
    
    const numericValue = parseFloat(inputValue.replace(/[^0-9.]/g, ''));
    if (!isNaN(numericValue) && numericValue >= 0 && numericValue <= MAX_MODEL_EARNINGS) {
      setModelEarnings(numericValue);
    }
  };

  /**
   * Handles blur event on earnings input to format and validate
   */
  const handleEarningsInputBlur = (): void => {
    const numericValue = parseFloat(earningsInputValue.replace(/[^0-9.]/g, '')) || 0;
    const clampedValue = Math.min(Math.max(0, numericValue), MAX_MODEL_EARNINGS);
    setModelEarnings(clampedValue);
    setEarningsInputValue(clampedValue.toString());
  };

  /**
   * Handles changes to the contribution score slider
   */
  const handleContributionChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    const value = Math.min(100, Math.max(0, Number(e.target.value)));
    setContributionScore(value);
  };

  /**
   * Handles changes to the exposure score slider
   */
  const handleExposureChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    const value = Math.min(100, Math.max(0, Number(e.target.value)));
    setExposureScore(value);
  };

  /**
   * Calculates projection value for a given scenario
   */
  const calculateProjectionValue = (scenario: ProjectionScenario): number => {
    return calculateAITouchValue(modelEarnings, scenario.contributionScore, scenario.exposureScore);
  };

  /**
   * Gets color class based on scenario type
   */
  const getScenarioColorClass = (name: string): string => {
    switch (name) {
      case 'Conservative':
        return 'bg-yellow-50 border-yellow-200';
      case 'Moderate':
        return 'bg-blue-50 border-blue-200';
      case 'Optimistic':
        return 'bg-green-50 border-green-200';
      default:
        return 'bg-gray-50 border-gray-200';
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-lg p-6">
      {/* Header Section */}
      <div className="flex items-center gap-2 mb-6">
        <Calculator className="w-6 h-6 text-blue-600" />
        <h2 className="text-xl font-bold text-gray-900">AI Touch Value™ Calculator</h2>
      </div>

      {/* Formula Breakdown Visual Display */}
      <div className="mb-6">
        <h3 className="text-sm font-semibold text-gray-700 mb-3">Formula Breakdown</h3>
        <div className="grid grid-cols-1 md:grid-cols-11 gap-2 items-center">
          {/* Box 1: Model Earnings */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 md:col-span-2">
            <div className="text-xs text-gray-600 mb-1">Model Earnings</div>
            <div className="text-sm font-semibold text-blue-800">
              {formatCurrency(modelEarnings, true)}
            </div>
          </div>

          {/* Multiplication Symbol */}
          <div className="hidden md:flex items-center justify-center text-xl font-bold text-gray-500">
            ×
          </div>

          {/* Box 2: Contribution Score */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 md:col-span-2">
            <div className="text-xs text-gray-600 mb-1">Contribution Score</div>
            <div className="text-sm font-semibold text-blue-800">
              {contributionScore}/100 = {(contributionScore / 100).toFixed(2)}
            </div>
          </div>

          {/* Multiplication Symbol */}
          <div className="hidden md:flex items-center justify-center text-xl font-bold text-gray-500">
            ×
          </div>

          {/* Box 3: Exposure Score */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 md:col-span-2">
            <div className="text-xs text-gray-600 mb-1">Exposure Score</div>
            <div className="text-sm font-semibold text-blue-800">
              {exposureScore}/100 = {(exposureScore / 100).toFixed(2)}
            </div>
          </div>

          {/* Multiplication Symbol */}
          <div className="hidden md:flex items-center justify-center text-xl font-bold text-gray-500">
            ×
          </div>

          {/* Box 4: Equity Factor */}
          <div className="bg-purple-50 border border-purple-200 rounded-lg p-3 md:col-span-2">
            <div className="text-xs text-gray-600 mb-1 flex items-center gap-1">
              Equity Factor
              <Info 
                className="w-3 h-3 text-gray-400 cursor-help" 
                aria-label="Fixed 25% creator compensation rate"
              />
            </div>
            <div className="text-sm font-semibold text-purple-800">
              0.25 (25%)
            </div>
          </div>
        </div>

        {/* Mobile Multiplication Indicators */}
        <div className="flex flex-col items-center md:hidden my-2">
          <span className="text-gray-500 font-bold">× × ×</span>
        </div>

        {/* Equals Sign and Result */}
        <div className="flex items-center gap-2 mt-4">
          <span className="text-2xl font-bold text-gray-500">=</span>
          <div className="flex-1 bg-green-50 border-2 border-green-300 rounded-lg p-4">
            <div className="text-xs text-gray-600 mb-1 flex items-center gap-1">
              <DollarSign className="w-3 h-3" />
              AI Touch Value™
            </div>
            <div className="text-2xl font-bold text-green-700">
              {formatCurrency(calculatedValue)}
            </div>
          </div>
        </div>
      </div>

      {/* Input Sliders Section (if editable) */}
      {editable && (
        <div className="space-y-6 mt-8 border-t pt-6">
          <h3 className="text-sm font-semibold text-gray-700 mb-4">Adjust Parameters</h3>
          
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Model Earnings Slider */}
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <label 
                  htmlFor="model-earnings-slider" 
                  className="text-sm font-medium text-gray-700 flex items-center gap-1"
                >
                  Model Earnings
                  <Info 
                    className="w-3 h-3 text-gray-400 cursor-help" 
                    aria-label="Total revenue generated by the AI model"
                  />
                </label>
                <span className="text-sm font-semibold text-blue-600">
                  {formatCurrency(modelEarnings, true)}
                </span>
              </div>
              
              <input
                id="model-earnings-slider"
                type="range"
                min="0"
                max={MAX_MODEL_EARNINGS}
                step={EARNINGS_STEP}
                value={modelEarnings}
                onChange={handleEarningsSliderChange}
                className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                aria-label={`Model earnings: ${formatCurrency(modelEarnings)}`}
                aria-valuemin={0}
                aria-valuemax={MAX_MODEL_EARNINGS}
                aria-valuenow={modelEarnings}
              />
              
              <div className="flex items-center gap-2 mt-2">
                <span className="text-xs text-gray-500">$</span>
                <input
                  type="text"
                  value={earningsInputValue}
                  onChange={handleEarningsInputChange}
                  onBlur={handleEarningsInputBlur}
                  className="flex-1 text-xs border rounded px-2 py-1 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Enter precise amount"
                  aria-label="Enter precise model earnings amount"
                />
              </div>
              
              <div className="flex justify-between text-xs text-gray-400">
                <span>$0</span>
                <span>$10M</span>
              </div>
            </div>

            {/* Contribution Score Slider */}
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <label 
                  htmlFor="contribution-score-slider"
                  className="text-sm font-medium text-gray-700 flex items-center gap-1"
                >
                  Training Contribution
                  <Info 
                    className="w-3 h-3 text-gray-400 cursor-help" 
                    aria-label="How much your asset contributed to training (0-100%)"
                  />
                </label>
                <span className="text-sm font-semibold text-blue-600">
                  {contributionScore}%
                </span>
              </div>
              
              <input
                id="contribution-score-slider"
                type="range"
                min="0"
                max="100"
                step="1"
                value={contributionScore}
                onChange={handleContributionChange}
                className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                aria-label={`Contribution score: ${contributionScore}%`}
                aria-valuemin={0}
                aria-valuemax={100}
                aria-valuenow={contributionScore}
              />
              
              <div className="flex justify-between text-xs text-gray-400">
                <span>0%</span>
                <span>50%</span>
                <span>100%</span>
              </div>
            </div>

            {/* Exposure Score Slider */}
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <label 
                  htmlFor="exposure-score-slider"
                  className="text-sm font-medium text-gray-700 flex items-center gap-1"
                >
                  Usage Exposure
                  <Info 
                    className="w-3 h-3 text-gray-400 cursor-help" 
                    aria-label="How frequently your asset was used in training (0-100%)"
                  />
                </label>
                <span className="text-sm font-semibold text-blue-600">
                  {exposureScore}%
                </span>
              </div>
              
              <input
                id="exposure-score-slider"
                type="range"
                min="0"
                max="100"
                step="1"
                value={exposureScore}
                onChange={handleExposureChange}
                className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                aria-label={`Exposure score: ${exposureScore}%`}
                aria-valuemin={0}
                aria-valuemax={100}
                aria-valuenow={exposureScore}
              />
              
              <div className="flex justify-between text-xs text-gray-400">
                <span>0%</span>
                <span>50%</span>
                <span>100%</span>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Projection Scenarios Section */}
      {editable && modelEarnings > 0 && (
        <div className="mt-8 border-t pt-6">
          <h3 className="text-sm font-semibold text-gray-700 mb-4">Projection Scenarios</h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {projectionScenarios.map((scenario) => (
              <div
                key={scenario.name}
                className={`rounded-lg border p-4 ${getScenarioColorClass(scenario.name)}`}
              >
                <div className="text-sm font-semibold text-gray-800 mb-1">
                  {scenario.name}
                </div>
                <div className="text-xs text-gray-600 mb-2">
                  {scenario.description}
                </div>
                <div className="text-xs text-gray-500 mb-1">
                  Contribution: {scenario.contributionScore}% | Exposure: {scenario.exposureScore}%
                </div>
                <div className="text-lg font-bold text-gray-900">
                  {formatCurrency(calculateProjectionValue(scenario))}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Explanation Panel (Collapsible) */}
      <div className="mt-8 border-t pt-6">
        <button
          onClick={() => setIsExplanationExpanded(!isExplanationExpanded)}
          className="flex items-center justify-between w-full text-left group"
          aria-expanded={isExplanationExpanded}
          aria-controls="explanation-panel"
        >
          <span className="text-sm font-semibold text-gray-700 flex items-center gap-2">
            <Info className="w-4 h-4 text-blue-600" />
            What is AI Touch Value™?
          </span>
          {isExplanationExpanded ? (
            <ChevronUp className="w-5 h-5 text-gray-400 group-hover:text-gray-600" />
          ) : (
            <ChevronDown className="w-5 h-5 text-gray-400 group-hover:text-gray-600" />
          )}
        </button>
        
        {isExplanationExpanded && (
          <div 
            id="explanation-panel"
            className="mt-4 bg-gray-50 rounded-lg p-4 text-sm text-gray-700 space-y-3"
          >
            <p>
              <strong>AI Touch Value™</strong> estimates your compensation based on your asset's 
              contribution to AI model training. It represents the monetary value you're entitled 
              to when AI companies use your creative work.
            </p>
            
            <div>
              <p className="font-semibold mb-2">Formula breakdown:</p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li>
                  <strong>Model Earnings:</strong> Total revenue generated by the AI model 
                  that used your content for training.
                </li>
                <li>
                  <strong>Training Contribution (0-100%):</strong> How much your asset 
                  contributed to the model's training data. Higher uniqueness and quality 
                  increase this score.
                </li>
                <li>
                  <strong>Usage Exposure (0-100%):</strong> How frequently your asset was 
                  encountered and used during training. More exposure means higher compensation.
                </li>
                <li>
                  <strong>Equity Factor (25%):</strong> Fixed creator compensation rate. 
                  This ensures creators receive a fair share of AI-generated revenue.
                </li>
              </ul>
            </div>
            
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mt-3">
              <p className="font-semibold text-blue-800 mb-1">Example Calculation:</p>
              <p className="text-blue-700">
                If a model earns <strong>$1,000,000</strong> and your asset has 
                <strong> 50% contribution</strong> and <strong>50% exposure</strong>, 
                your AI Touch Value™ would be:
              </p>
              <p className="font-mono text-blue-900 mt-2">
                $1,000,000 × 0.50 × 0.50 × 0.25 = <strong>$62,500.00</strong>
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AITouchValue;
